#!/usr/bin/python

import paramiko
 
try:
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    print "Trying to connect to node ...  "
    ssh.connect('68.128.156.119', username='zarvis', password='user1234')
    print "Connection established !"
    ftp = ssh.open_sftp()
    file=ftp.file('my.txt', "a", -1)
    file.write("[Unit] \n")
    file.write("Description=Hello World \n")
    file.write("[Service] \n")
    file.write("ExecStart=/bin/bash -c \"while true; do echo \"Hello, world\"; sleep 1; done\" \n")
    file.flush()
    print "File created ..."
except paramiko.SSHException:
    print "Failed to connect remote node ..."
 
except IOError:
    print "Unable to create hello.service file in node ..."
 
finally:
    ftp.close()
    ssh.close()
    print "Active SSH connection closed !"
